

export  const ORDER_ACTION_TYPE = {
    CREATE_ORDER_START : 'CREATE_ORDER_START',
    CREATE_ORDER_SUCCESS : 'CREATE_ORDER_SUCCESS',
    CREATE_ORDER_FAILED : 'CREATE_ORDER_FAILED',

    MY_ORDERS_START : 'MY_ORDERS_START',
    MY_ORDERS_SUCCESS : 'MY_ORDERS_SUCCESS',
    MY_ORDERS_FAILED : 'MY_ORDERS_FAILED',


        ORDER_DETAILS_START : 'ORDER_DETAILS_START',
    ORDER_DETAILS_SUCCESS : 'ORDER_DETAILS_SUCCESS',
    ORDER_DETAILS_FAILED : 'CREATE_ORDER_FAILED',
    CLEAR_ERRORS : 'CLEAR_ERRORS',

}

 