

export  const ORDER_ACTION_TYPE = {
    CREATE_ORDER_START : 'CREATE_ORDER_START',
    CREATE_ORDER_SUCCESS : 'CREATE_ORDER_SUCCESS',
    CREATE_ORDER_FAILED : 'CREATE_ORDER_FAILED',


    MY_ORDERS_START : 'MY_ORDERS_START',
    MY_ORDERS_SUCCESS : 'MY_ORDERS_SUCCESS',
    MY_ORDERS_FAILED : 'MY_ORDERS_FAILED',


    ALL_ORDERS_START : 'ALL_ORDERS_START',
    ALL_ORDERS_SUCCESS : 'ALL_ORDERS_SUCCESS',
    ALL_ORDERS_FAILED : 'ALL_ORDERS_FAILED',

    UPDATE_ORDER_START : 'UPDATE_ORDER_START',
    UPDATE_ORDER_SUCCESS : 'UPDATE_ORDER_SUCCESS',
    UPDATE_ORDER_RESET : 'UPDATE_ORDER_RESET',
    UPDATE_ORDER_FAILED : 'UPDATE_ORDER_FAILED',

    DELETE_ORDER_START : 'DELETE_ORDER_START',
    DELETE_ORDER_SUCCESS : 'DELETE_ORDER_SUCCESS',
    DELETE_ORDER_RESET : 'DELETE_ORDER_RESET',
    DELETE_ORDER_FAILED : 'DELETE_ORDER_FAILED',


        ORDER_DETAILS_START : 'ORDER_DETAILS_START',
    ORDER_DETAILS_SUCCESS : 'ORDER_DETAILS_SUCCESS',
    ORDER_DETAILS_FAILED : 'CREATE_ORDER_FAILED',
    CLEAR_ERRORS : 'CLEAR_ERRORS',

}

