export  const ORDER_ACTION_TYPE = {
    CREATE_ORDER_START : 'CREATE_ORDER_START',
    CREATE_ORDER_SUCCESS : 'CREATE_ORDER_SUCCESS',
    CREATE_ORDER_FAILED : 'CREATE_ORDER_FAILED',
    CLEAR_ERRORS : 'CLEAR_ERRORS',

}