
export  const USERS_ACTION_TYPE = {
    LOGIN_USER_START : 'LOGIN_USER_START',
    LOGIN_USER_SUCCESS : 'LOGIN_USER_SUCCESS',
    LOGIN_USER_FAILED : 'LOGIN_USER_FAILED',


    REGISTER_USER_START : 'REGISTER_USER_START',
    REGISTER_USER_SUCCESS : 'REGISTER_USER_SUCCESS',
    REGISTER_USER_FAILED : 'REGISTER_USER_FAILED',
    

       LOAD_USER_START : 'LOAD_USER_START',
    LOAD_USER_SUCCESS : 'LOAD_USER_SUCCESS',
    LOAD_USER_FAILED : 'LOAD_USER_FAILED',



    LOGOUT_USER_START : 'LOGOUT_USER_START',
    LOGOUT_USER_SUCCESS : 'LOGOUT_USER_SUCCESS',
    LOGOUT_USER_FAILED : 'LOGOUT_USER_FAILED',

    CLEAR_ERRORS : 'CLEAR_ERRORS',


}