
export  const USERS_ACTION_TYPE = {
    LOGIN_USER_START : 'LOGIN_USER_START',
    LOGIN_USER_SUCCESS : 'LOGIN_USER_SUCCESS',
    LOGIN_USER_FAILED : 'LOGIN_USER_FAILED',


    REGISTER_USER_START : 'REGISTER_USER_START',
    REGISTER_USER_SUCCESS : 'REGISTER_USER_SUCCESS',
    REGISTER_USER_FAILED : 'REGISTER_USER_FAILED',
    

       LOAD_USER_START : 'LOAD_USER_START',
    LOAD_USER_SUCCESS : 'LOAD_USER_SUCCESS',
    LOAD_USER_FAILED : 'LOAD_USER_FAILED',

    FORGOT_PASSWORD_START : 'FORGOT_PASSWORD_START',
    FORGOT_PASSWORD_SUCCESS : 'FORGOT_PASSWORD_SUCCESS',
    FORGOT_PASSWORD_FAILED : 'FORGOT_PASSWORD_FAILED',

    NEW_PASSWORD_START : 'NEW_PASSWORD_START',
    NEW_PASSWORD_SUCCESS : 'NEW_PASSWORD_SUCCESS',
    NEW_PASSWORD_FAILED : 'NEW_PASSWORD_FAILED',

    UPDATE_PROFILE_START : 'UPDATE_PROFILE_START',
    UPDATE_PROFILE_SUCCESS : 'UPDATE_PROFILE_SUCCESS',
    UPDATE_PROFILE_RESET : 'UPDATE_PROFILE_RESET',
    UPDATE_PROFILE_FAILED : 'UPDATE_PROFILE_FAILED',

    UPDATE_PASSWORD_START : 'UPDATE_PASSWORD_START',
    UPDATE_PASSWORD_SUCCESS : 'UPDATE_PASSWORD_SUCCESS',
    UPDATE_PASSWORD_FAILED : 'UPDATE_PASSWORD_FAILED',

    LOGOUT_USER_START : 'LOGOUT_USER_START',
    LOGOUT_USER_SUCCESS : 'LOGOUT_USER_SUCCESS',
    LOGOUT_USER_FAILED : 'LOGOUT_USER_FAILED',

    CLEAR_ERRORS : 'CLEAR_ERRORS',


}