
export  const PRODUCTS_ACTION_TYPE = {
    FETCH_ALL_PRODUCTS_START : 'FETCH_ALL_PRODUCTS_START',
    FETCH_ALL_PRODUCTS_SUCCESS : 'FETCH_ALL_PRODUCTS_SUCCESS',
    FETCH_ALL_PRODUCTS_FAILED : 'FETCH_ALL_PRODUCTS_FAILED',


    FETCH_PRODUCT_DETAILS_START : 'FETCH_PRODUCT_DETAILS_START',
    FETCH_PRODUCT_DETAILS_SUCCESS : 'FETCH_PRODUCT_DETAILS_SUCCESS',
    FETCH_PRODUCT_DETAILS_FAILED : 'FETCH_ALL_PRODUCT_DETAILS_FAILED',



    NEW_REVIEW_DETAILS_START : 'NEW_REVIEW_DETAILS_START',
    NEW_REVIEW_DETAILS_SUCCESS : 'NEW_REVIEW_DETAILS_SUCCESS',
    NEW_REVIEW_DETAILS_FAILED : 'NEW_ALL_REVIEW_DETAILS_FAILED',
    NEW_REVIEW_DETAILS_RESET : 'NEW_ALL_REVIEW_DETAILS_RESET',

    CLEAR_ERRORS : 'CLEAR_ERRORS',
}