
export  const PRODUCTS_ACTION_TYPE = {
    FETCH_ALL_PRODUCTS_START : 'FETCH_ALL_PRODUCTS_START',
    FETCH_ALL_PRODUCTS_SUCCESS : 'FETCH_ALL_PRODUCTS_SUCCESS',
    FETCH_ALL_PRODUCTS_FAILED : 'FETCH_ALL_PRODUCTS_FAILED',
    CLEAR_ERRORS : 'CLEAR_ERRORS',

}