
export  const PRODUCTS_ACTION_TYPE = {

        
    ADMIN_PRODUCTS_START : 'ADMIN_PRODUCTS_START',
    ADMIN_PRODUCTS_SUCCESS : 'ADMIN_PRODUCTS_SUCCESS',
    ADMIN_PRODUCTS_FAILED : 'ADMIN_PRODUCTS_FAILED',

    
    FETCH_ALL_PRODUCTS_START : 'FETCH_ALL_PRODUCTS_START',
    FETCH_ALL_PRODUCTS_SUCCESS : 'FETCH_ALL_PRODUCTS_SUCCESS',
    FETCH_ALL_PRODUCTS_FAILED : 'FETCH_ALL_PRODUCTS_FAILED',


    FETCH_PRODUCT_DETAILS_START : 'FETCH_PRODUCT_DETAILS_START',
    FETCH_PRODUCT_DETAILS_SUCCESS : 'FETCH_PRODUCT_DETAILS_SUCCESS',
    FETCH_PRODUCT_DETAILS_FAILED : 'FETCH_ALL_PRODUCT_DETAILS_FAILED',


    NEW_PRODUCT_START : 'NEW_PRODUCT_START',
    NEW_PRODUCT_SUCCESS : 'NEW_PRODUCT_SUCCESS',
    NEW_PRODUCT_FAILED : 'NEW_PRODUCT_FAILED',
    NEW_PRODUCT_RESET : 'NEW_PRODUCT_RESET',


    DELETE_PRODUCT_START : 'DELETE_PRODUCT_START',
    DELETE_PRODUCT_SUCCESS : 'DELETE_PRODUCT_SUCCESS',
    DELETE_PRODUCT_FAILED : 'DELETE_PRODUCT_FAILED',
    DELETE_PRODUCT_RESET : 'DELETE_PRODUCT_RESET',

    UPDATE_PRODUCT_START : 'UPDATE_PRODUCT_START',
    UPDATE_PRODUCT_SUCCESS : 'UPDATE_PRODUCT_SUCCESS',
    UPDATE_PRODUCT_FAILED : 'UPDATE_PRODUCT_FAILED',
    UPDATE_PRODUCT_RESET : 'UPDATE_PRODUCT_RESET',




    NEW_REVIEW_DETAILS_START : 'NEW_REVIEW_DETAILS_START',
    NEW_REVIEW_DETAILS_SUCCESS : 'NEW_REVIEW_DETAILS_SUCCESS',
    NEW_REVIEW_DETAILS_FAILED : 'NEW_REVIEW_DETAILS_FAILED',
    NEW_REVIEW_DETAILS_RESET : 'NEW_REVIEW_DETAILS_RESET',

    CLEAR_ERRORS : 'CLEAR_ERRORS',
}